apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: brain-chaos-local
  namespace: argocd
spec:
  project: brain-chaos-lab
  source:
    repoURL: https://github.com/PydaVi/brain-chaos.git
    targetRevision: main
    path: k8s/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: lab-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
