server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /health/web-frontend {
    proxy_pass http://web-frontend;
  }

  location /health/api-gateway {
    proxy_pass http://api-gateway;
  }

  location /health/orders-service {
    proxy_pass http://orders-service;
  }

  location /health/catalog-service {
    proxy_pass http://catalog-service;
  }

  location /health/payments-mock {
    proxy_pass http://payments-mock;
  }
}
