apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ../../base
  - ../../apps/web-frontend
  - ../../apps/api-gateway
  - ../../apps/orders-service
  - ../../apps/catalog-service
  - ../../apps/payments-mock
  - ../../apps/redis
  - ../../apps/postgres

images:
  - name: web-frontend
    newName: ghcr.io/pydavi/brain-chaos/web-frontend
    newTag: ui-v1-202602242359
