apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lab-app

resources:
  - ../../base
  - ../../apps/web-frontend

images:
  - name: web-frontend
    newName: ghcr.io/pydavi/brain-chaos/web-frontend
    newTag: dev
