apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-mock
  labels:
    app: payments-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-mock
  template:
    metadata:
      labels:
        app: payments-mock
    spec:
      serviceAccountName: lab-app-sa
      volumes:
        - name: tmp
          emptyDir: {}
        - name: content
          configMap:
            name: payments-mock-index
      containers:
        - name: payments-mock
          image: nginxinc/nginx-unprivileged:1.27-alpine
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: content
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
