apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: httpbin-l7
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      run: httpbin
  ingress:
    - fromEndpoints:
        - matchLabels:
            run: curl
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
          rules:
            http:
              - method: "GET"
                path: "/headers"
