apiVersion: v1
kind: ResourceQuota
metadata:
  name: lab-observability-quota
  namespace: lab-observability
spec:
  hard:
    limits.cpu: "1"
    limits.memory: 2Gi
    requests.cpu: 500m
    requests.memory: 1Gi
    pods: "10"
