apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  # Aponta para o install.yaml oficial do ArgoCD (canal stable).
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
