apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/lab-app.yaml
  - quotas/lab-app-resourcequota.yaml
  - limits/lab-app-limitrange.yaml
  - serviceaccounts/lab-app-sa.yaml
