apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: lab-observability
  labels:
    app: blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
        - name: blackbox-exporter
          image: prom/blackbox-exporter:v0.25.0
          args:
            - --config.file=/etc/blackbox/blackbox.yml
          ports:
            - containerPort: 9115
          volumeMounts:
            - name: config
              mountPath: /etc/blackbox/blackbox.yml
              subPath: blackbox.yml
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 96Mi
          readinessProbe:
            httpGet:
              path: /-/healthy
              port: 9115
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: blackbox-config
