apiVersion: v1
kind: ResourceQuota
metadata:
  name: lab-app-quota
  namespace: lab-app
spec:
  hard:
    limits.cpu: "3"
    limits.memory: 4Gi
    requests.cpu: "1"
    requests.memory: 2Gi
    pods: "20"
